title: "Epidemic modelling &ndash; Some notes, maths, and code"
author: "Simon Dobson"
email: simon.dobson@st-andrews.ac.uk
copyright: "2020"
#logo: logo.png

repository:
  url: https://github.com/simoninireland/introduction-to-epidemics
  path_to_book: ""
  branch: "master"

google_analytics:
  mytrackingcode: UA-42241903-2
  
launch_buttons:
  notebook_interface: "classic"
  
execute:
  execute_notebooks: "off"
  
latex:
  latex_documents:
    targetname: book.tex
